Search page
macebm/capstone-project pull request #18
Opened 2020-12-21 04:44 UTC by macebm

Fixes from last PR and some style changes. 

Now new page Search page. You can click on a category and get all products with it

2020-12-21 07:54 UTC, web-devil requested changes

2020-12-21 07:54 UTC, web-devil commented on frontend/src/components/GlobalStyle.js
> +        background: url("https://cdn.pixabay.com/photo/2019/05/06/19/13/green-4183977_1280.jpg");
lieber im repository hinterlegen

2020-12-21 07:54 UTC, web-devil commented on frontend/src/components/Search.js
> +  function handleCategory(categoryId) {
leerzeile

2020-12-21 14:01 UTC, ThomasKirst reviewed
Overall very good! Just a few remarks about naming of components.

You can .gitignore this file: .DS_Store 

Great Job! Miriam says: 😸

2020-12-21 14:01 UTC, ThomasKirst commented on frontend/src/components/CategoryButton.js
> +  return <Wrapper onClick={() => onClick(id)}>{children}</Wrapper>;
```suggestion
  return <Button onClick={() => onClick(id)}>{children}</Button>;
```
`Wrapper` is not a great component name, you could rather use `Button`, for instance.

2020-12-21 14:01 UTC, ThomasKirst commented on frontend/src/components/CategoryButton.js
> +import Colors from "../constants/Colors";
Reconsider fully capitalised letters as constants should be declared as such.

2020-12-21 14:01 UTC, ThomasKirst commented on frontend/src/components/ProductWithStore.js
> +    <Wrapper>
Another `Wrapper` – why not `Product` or `ProductCard`?

2020-12-21 14:01 UTC, ThomasKirst commented on frontend/src/components/Search.js
> +    <Wrapper>
Is this a `<SearchPage…` or really another `Wrapper`?

2020-12-21 14:01 UTC, ThomasKirst commented on frontend/src/components/Search.js
> +  margin-bottom: 3.75rem;
`rem`s to the rescue! We like 👍

2020-12-21 14:01 UTC, ThomasKirst commented on frontend/src/components/SingleStore.js
>        <StyledProductBox>
```suggestion
      <ProductBox>
```
For sure it's going to be styled ;)

2020-12-21 14:01 UTC, ThomasKirst commented on frontend/src/components/SingleStore.js
>      </StyledSection>
```suggestion
    </Section>
```

2020-12-21 14:35 UTC, macebm commented on frontend/src/components/Search.js
> +    <Wrapper>
Its a page

2020-12-21 14:45 UTC, macebm commented on frontend/src/components/CategoryButton.js
> +  return <Wrapper onClick={() => onClick(id)}>{children}</Wrapper>;
Changed it for all thank you 🍀

2020-12-22 14:09 UTC, miriamhaenle approved these changes

2021-01-11 11:13 UTC, merged